name: compile-docusaurus-static-assets

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify-docusaurus-static-files:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        # `uses` taps GH ORG/REPO@version.
        # "actions" is a default org for some common GH actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set node-version
        shell: bash
        run: echo "NODE_VERSION="$(cat .node-version)"" >> $GITHUB_ENV
      # Node is required for yarn
      - name: Set up Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "yarn"
          cache-dependency-path: docusaurus
      # Install and build Docusaurus website
      - name: Check for docusaurus changes
        run: ./tools/bin/check_docusaurus_build_changes
